config/routes.rb
Blog::Application.routes.draw do
  devise_for :users

  get "post/index"

  match "post/show/:id/" => "post#show", :via => :get , :as => "show_post"

  get "post/edit"

  get "post/list"

  get "post/new", :as => "posts"
  post "post/create", :as => "posts"

   get "user/:id" =>"home#user", :as => "user"
   get "user/follow/:id" =>"home#follow", :as => "follow"
   get "user/unfollow/:id" =>"home#unfollow", :as => "unfollow"
   get "users" =>"home#users"
   delete "post/:id" => "post#destroy", :as => "destroy_post"

  root :to => 'home#index'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post_categories
	has_many :posts, through: :post_categories

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :post_categories
	has_many :categories, through: :post_categories
	belongs_to :user
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_followable
  acts_as_follower
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
         return_to = session[:return_to] ||  post_list_url
 end

 def after_sign_out_path_for(resource)
         root_url
 end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
	def user
		@user = User.find_by_id(params[:id])
	end
	def users
		@users = User.all
	end


	def follow
		@user = User.find_by_id(params[:id])
		if !current_user.following?(@user)
			current_user.follow(@user)
		end
		redirect_to(:back)
	end

	def unfollow
		@user = User.find_by_id(params[:id])
		if current_user.following?(@user)
			 current_user.stop_following(@user)
		end
		redirect_to(:back)
	end

end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end

  def new
  	@post = Post.new()
  end

  def create
  	@post = Post.new(params[:post])
    @post.user_id = current_user.id
    logger.info("User: #{@post.user_id} , Current User: #{current_user.id}")

  	@post.save()
    logger.info("User: #{@post.user_id} , Current User: #{current_user.id}")
  	redirect_to show_post_path(@post)
  end

  def show
  	@post = Post.find_by_id(params[:id])
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy

    redirect_to post_list_url
  end

  def list
  	@post = Post.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_gravatar(user=current_user, size=96)
               image_tag "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{size}"
       end
end

app/helpers/home_helper.rb
module HomeHelper
	def follow_or_unfollow(user)
		if current_user.following?(user)
			link_to("Unfollow", unfollow_url(user),:class=>"btn btn-danger")
		else
			link_to("Follow", follow_url(user),:class=>"btn btn-success")
		end
	end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/home/index.html.erb
<div class="hero-unit">
	<h1> Blog Social</h1>
	<%= link_to("Join us!", new_user_registration_url, :class=>"btn btn-primary") if !user_signed_in? %>
</div>

app/views/home/user.html.erb
<h2>Your Profile</h2>
<%=get_gravatar(@user) %>
<h3><%=@user.email%></h3> <%=  %>

<% if user_signed_in?%>

	<% if current_user == @user %>
		<h3><%= link_to("Edit", edit_user_registration_url)  %></h3>
	
	<%else %>
		<%= follow_or_unfollow(@user) %>

	<% end %>
<% end %>

<div class="row">
	<div class="span4">
		<h3>Following</h3>
		<% @user.all_following.each do |u| %>
		 <p><%= link_to(u.email, user_url(u)) %></p>
		 <% end %>
	</div>
	<div class="span4">
		<h3>Followers</h3>
		<% @user.followers.each do |u| %>
		 <p><%= link_to(u.email, user_url(u)) %></p>
		 <% end %>
	</div>
</div>

app/views/home/users.html.erb
<div class="row">
	<div class="span4">
		<% @users.each do |u| %>
		<div class="well"><%= get_gravatar(u) +u.email %> </div>
		<% end %>
	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_url %>">Blog</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Posts", post_list_url  %></li>
              <li><%= link_to "Users", users_url  %></li>
            </ul>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li><%= link_to current_user.email,user_url(current_user) %></li>
                <li><%= link_to "Logout", destroy_user_session_url, :method => :delete %></li>
           <% else %>
             <li><%= link_to "Login", new_user_session_url %></li>
           <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Milfont Consulting 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/post/_form.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :conteudo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :conteudo, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
               post_list_url, :class => 'btn' %>
  </div>
<% end %>

app/views/post/edit.html.erb
<%- model_class = @post.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/post/index.html.erb
<%- model_class = Post.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:conteudo) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.nome %></td>
        <td><%= post.conteudo %></td>
        <td><%=l post.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/post/list.html.erb
<h1>Listagem dos posts</h1>
<%= link_to("Create a Post", :controller => "post" , :action=> "new") %>
<ul>
	<div class="row">
		<% @post.each do |x| %>
		<div class="well">
		<li>
			<div class="span10">
				<h3><%=  link_to x.nome , show_post_path(x) %></h3>
				<p><%= x.conteudo %></p>
			</div> 
			<div class="span2">
				<%= get_gravatar(x.user,48) %>
			</div>
		</li>
		<br/> <br/>
		</div>
		<% end %>
	</div>
</ul>

app/views/post/new.html.erb
<%- model_class = @post.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/post/show.html.erb
<%- model_class = @post.class -%>
<div class="page-header">
  <h1><%= @post.nome %></h1>
  <%= link_to(@post.user.email, user_url(@post.user)) %>
</div>

  <div class="well">
  		<%= @post.conteudo %>
  </div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              post_list_url, :class => 'btn'  %>
  <%= link_to('Delete', destroy_post_path(@post), :method=>"delete", :class => 'btn btn-danger') %>
</div>